//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ovoch.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ovoch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0eL77NcVufuDKbEW9DfryZcGlQ_bXZAUzFhyq_8wlFTxqK_wOZ_uR4sMOizT48s8xQM2q36nsykhdtIC7QS6QbJN {
            get {
                object obj = ResourceManager.GetObject("0eL77NcVufuDKbEW9DfryZcGlQ-bXZAUzFhyq_8wlFTxqK_wOZ-uR4sMOizT48s8xQM2q36nsykhdtIC7" +
                        "QS6QbJN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1571004123_875619 {
            get {
                object obj = ResourceManager.GetObject("1571004123_875619", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1616988818_4_p_fon_dlya_prilozheniya_4 {
            get {
                object obj = ResourceManager.GetObject("1616988818_4-p-fon-dlya-prilozheniya-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcXI5Z74RbtwTExfwV_yzLxLmz63BAcWSo42FI6gD_npplbUOm_FxdB3Y7nOa6K_5tnO3TaC {
            get {
                object obj = ResourceManager.GetObject("IcXI5Z74RbtwTExfwV_yzLxLmz63BAcWSo42FI6gD-npplbUOm_FxdB3Y7nOa6K-5tnO3TaC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OY8s_7ZxTuf0b4_vJ1vwIOk2UBbU0KmsPMnjsJebr5UygNJVfwzVu60KoOTPGaKOyb5eOl86MJRX9sPDB9OU5Ldo {
            get {
                object obj = ResourceManager.GetObject("OY8s_7ZxTuf0b4-vJ1vwIOk2UBbU0KmsPMnjsJebr5UygNJVfwzVu60KoOTPGaKOyb5eOl86MJRX9sPDB" +
                        "9OU5Ldo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap suaD_p8zcqvLUcYX291CIUjdLiREpS2xJw55eVXzFRmUeOWwM6_fL9sqUD8srxIburLLeWDPO0WpVIw0QejrpmW9 {
            get {
                object obj = ResourceManager.GetObject("suaD_p8zcqvLUcYX291CIUjdLiREpS2xJw55eVXzFRmUeOWwM6-fL9sqUD8srxIburLLeWDPO0WpVIw0Q" +
                        "ejrpmW9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок_экрана__3_ {
            get {
                object obj = ResourceManager.GetObject("Снимок экрана (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
